name: Build & deploy to dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: npm ci && REACT_APP_STOREURL=https://win11react.github.io/experimental/dev-store.json npm run ghbuild

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          cname: dev.blueedge.me
          external_repository: win11bot/dev-build
          publish_dir: ./build
