name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### 👷 Deploy Preview for win11react processing.

            | Name | Link |
            |-|-|
            | 🔨 Latest commit | ${{ github.event.pull_request.head.sha }} |
            | 🔍 Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |

          GITHUB_TOKEN: ${{ secrets.BOT }}

      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - if: ${{ github.event.action == 'opened'}}
        run: gh repo create win11bot/${{ github.event.pull_request.number }} --public
        env:
          GITHUB_TOKEN: ${{ secrets.BOT }}

      - name: Install NPM packages
        run: npm ci

      - name: Get translations
        run: npm run crowdin download
        env:
          api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Build project
        run: npm run ghbuild
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BOT }}
          publish_dir: ./build
          external_repository: win11bot/${{ github.event.pull_request.number }}

      - name: Sleep to make sure page gets updated
        run: sleep 1m
        shell: bash

      - name: comment Preview Ready
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### ✅ Deploy Preview for win11react ready!

            | Name | Link |
            |-|-|
            | 🔨 Latest commit | ${{ github.event.pull_request.head.sha }} |
            | 🔍 Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | 😎 Deploy Preview | https://pr-preview.win11react.com/${{ github.event.pull_request.number }} |

          GITHUB_TOKEN: ${{ secrets.BOT }}

      - if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### ❌ Deploy Preview for win11react failed.

            | Name | Link |
            |-|-|
            | 🔨 Latest commit | ${{ github.event.pull_request.head.sha }} |
            | 🔍 Latest deploy log | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |

          GITHUB_TOKEN: ${{ secrets.BOT }}
